In [2]:
import numpy as np
a=[]
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [3]:
a

array([0, 1, 2, 3, 4])

In [6]:
def numsum(n):
   a=np.arange(n)**2
   b=np.arange(n)**3
   c=a+b
   return c
numsum(10)



array([  0,   2,  12,  36,  80, 150, 252, 392, 576, 810])

In [7]:
a=np.arange(10)
a.dtype

dtype('int32')

In [8]:
a.shape

(10,)

In [28]:
import numpy as np

a=np.array([[4,6],[2,4]])
a

array([[4, 6],
       [2, 4]])

In [34]:
m = np.array([[arange(2)], [arange(2)]]) 
m     

NameError: name 'arange' is not defined

In [40]:
t = np.dtype([('name', np.str_, 40), ('numitems', np.int32), ('price',
np.float32)])
t

dtype([('name', '<U40'), ('numitems', '<i4'), ('price', '<f4')])

In [41]:
t['name']

dtype('<U40')

In [42]:
t['numitems']

dtype('int32')

In [51]:
b=np.arange(24).reshape(2,3,4)

In [52]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [56]:
b[:,2,3]

array([11, 23])

In [57]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [58]:
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [59]:
b.flatten

<function ndarray.flatten>

In [60]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [61]:
b.flatten

<function ndarray.flatten>

In [62]:
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [63]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [64]:
b.flat

In [65]:
b.ravel()


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [66]:
b.flatten

<function ndarray.flatten>

In [67]:
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [68]:
a=np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [69]:
b=a*2
b

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [73]:
np.hstack((a,b))


array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [74]:
np.vstack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [75]:
b


array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [76]:
b.flat[2]

4

In [77]:
b.flat[1]

2

In [2]:
import numpy as np
b=np.arange(24).reshape(2,3,4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [3]:
b[0,1,::2]

array([4, 6])

In [4]:
b[0,1,2]

6

In [5]:
b=np.arange(27).reshape(3,3,3)
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [12]:
np.dsplit(b,3)

[array([[[ 0],
         [ 3],
         [ 6]],
 
        [[ 9],
         [12],
         [15]],
 
        [[18],
         [21],
         [24]]]), array([[[ 1],
         [ 4],
         [ 7]],
 
        [[10],
         [13],
         [16]],
 
        [[19],
         [22],
         [25]]]), array([[[ 2],
         [ 5],
         [ 8]],
 
        [[11],
         [14],
         [17]],
 
        [[20],
         [23],
         [26]]])]

In [34]:
from __future__ import print_function
c,v=np.loadtxt('data.csv',delimiter=',',usecols=(6,7),unpack=True)
vwap = np.average(c,weights=v) 
print("VWAP=",vwap)
#note that the counting of columns in csv file always starts from 1 not 0

VWAP= 336.1


In [28]:
print("mean =", np.mean(c)) 

mean = 336.1


In [2]:
import numpy as np
a=np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [3]:
a.reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [5]:
np.ones_like(a)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

In [6]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [9]:
np.zeros_like(a)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [10]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.eye(24)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 

In [13]:
np.eye(500)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [14]:
np.empty_like(a)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [18]:
a=np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [23]:

arr1=np.array([1,2,3,4,5],dtype=np.int64)

In [24]:
arr1

array([1, 2, 3, 4, 5], dtype=int64)

In [26]:
arr2=[1,2,3,4,]
b=np.array(arr2,dtype='int64')

In [27]:
b

array([1, 2, 3, 4], dtype=int64)

In [33]:
b.dtype

dtype('int64')

In [34]:
type('Mubashir')

str

In [35]:
type('Shut the fuck up')

str

In [36]:
float_arr=arr1.astype('float64')

In [37]:
arr1.dtype

dtype('int64')

In [38]:
float_arr

array([1., 2., 3., 4., 5.])

In [40]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [41]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [42]:
arr*arr

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100]])

In [43]:
arr**2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100]], dtype=int32)

In [44]:
arr**3

array([[   1,    8,   27,   64,  125],
       [ 216,  343,  512,  729, 1000]], dtype=int32)

In [48]:
arr2=np.array([[3,2,4,9,8],[7,3,11,16,56]])

In [64]:
a=arr2>arr
a

array([[ True, False,  True,  True,  True],
       [ True, False,  True,  True,  True]])

In [65]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [66]:
arr2.sort

<function ndarray.sort>

In [67]:
a=arr2.sort

In [68]:
a

<function ndarray.sort>

In [58]:
a

<function ndarray.sort>

In [59]:
a=sorted(arr2)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [60]:
a.any(arr2)

AttributeError: 'builtin_function_or_method' object has no attribute 'any'

In [61]:
a.any()

AttributeError: 'builtin_function_or_method' object has no attribute 'any'

In [69]:
a=np.dtype('?')

In [71]:
print(a)

bool


In [80]:
arr=list(range(10))

In [81]:
arr

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [82]:
arr[5:8]

[5, 6, 7]

In [83]:
arr[-1:8]

[]

In [84]:
arr[:-1]

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [85]:
arr[-1:-3]

[]

In [86]:
arr[5:8]=12

TypeError: can only assign an iterable

In [87]:
arr=np.arange(10)

In [88]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
arr=list(range(10))

In [91]:
arr

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [98]:
arr[2:5]=[64,3,5,100]

In [99]:
arr

[0, 1, 64, 3, 5, 100, 5, 6, 7, 8, 9]

In [104]:
arr3d=np.array([[[1,2,3],[4,5,6],['a','b','c']],[[7,8,9],[10,11,12],['d','e','f']]])

In [105]:
arr3d

array([[['1', '2', '3'],
        ['4', '5', '6'],
        ['a', 'b', 'c']],

       [['7', '8', '9'],
        ['10', '11', '12'],
        ['d', 'e', 'f']]], dtype='<U11')

In [106]:
arr3d[0]

array([['1', '2', '3'],
       ['4', '5', '6'],
       ['a', 'b', 'c']], dtype='<U11')

In [107]:
arr3d[1]

array([['7', '8', '9'],
       ['10', '11', '12'],
       ['d', 'e', 'f']], dtype='<U11')

In [109]:
arr3d[0,1,1]

'5'

In [110]:
arr3d[1,1,:2]

array(['10', '11'], dtype='<U11')

In [111]:
arr3d[0,1,:]

array(['4', '5', '6'], dtype='<U11')

In [112]:
arr3d[0,:,0]

array(['1', '4', 'a'], dtype='<U11')

In [113]:
a=arr3d[0,:,:]

In [114]:
a

array([['1', '2', '3'],
       ['4', '5', '6'],
       ['a', 'b', 'c']], dtype='<U11')

In [115]:
b=arr3d[1,:,:]

In [116]:
b

array([['7', '8', '9'],
       ['10', '11', '12'],
       ['d', 'e', 'f']], dtype='<U11')

In [123]:
np.size(arr3d)

18

In [124]:
c=np.arange(36).reshape(6,6)
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

i=np.eye(6,dtype='?)


In [126]:
i=np.eye(6,dtype='?')
i

array([[ True, False, False, False, False, False],
       [False,  True, False, False, False, False],
       [False, False,  True, False, False, False],
       [False, False, False,  True, False, False],
       [False, False, False, False,  True, False],
       [False, False, False, False, False,  True]])

In [127]:
c[i]

array([ 0,  7, 14, 21, 28, 35])

In [128]:
i=np.eye(3,dtype='?')

In [129]:
i

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [131]:
arr3d[0,i]

array(['1', '5', 'c'], dtype='<U11')

In [132]:
arr3d[1,i]

array(['7', '11', 'f'], dtype='<U11')

In [134]:
names=np.array(['bob','joe','will','bob','will','joe','joe'])
data=np.random.randn(7,4)

In [135]:
names

array(['bob', 'joe', 'will', 'bob', 'will', 'joe', 'joe'], dtype='<U4')

In [136]:
data

array([[-0.85415932, -0.00908086,  0.19160657,  2.20237169],
       [ 0.77026201,  0.1059384 ,  0.18234367, -0.20527532],
       [ 0.75755567, -0.54841877,  1.50083331, -0.44885624],
       [-1.37573701,  0.18685764,  0.69836101, -1.73121035],
       [-1.34946915, -0.18323707, -0.09119725,  0.91827558],
       [ 0.67346525,  0.96891116, -0.01437648, -1.59569342],
       [-1.48070486, -1.8901319 , -1.19306552,  0.94028598]])

In [137]:
data[names=='bob']

array([[-0.85415932, -0.00908086,  0.19160657,  2.20237169],
       [-1.37573701,  0.18685764,  0.69836101, -1.73121035]])

In [139]:
names!='bob'

array([False,  True,  True, False,  True,  True,  True])

In [140]:
data[names!='bob']

array([[ 0.77026201,  0.1059384 ,  0.18234367, -0.20527532],
       [ 0.75755567, -0.54841877,  1.50083331, -0.44885624],
       [-1.34946915, -0.18323707, -0.09119725,  0.91827558],
       [ 0.67346525,  0.96891116, -0.01437648, -1.59569342],
       [-1.48070486, -1.8901319 , -1.19306552,  0.94028598]])

In [143]:
a=data.transpose()

In [144]:
a

array([[-0.85415932,  0.77026201,  0.75755567, -1.37573701, -1.34946915,
         0.67346525, -1.48070486],
       [-0.00908086,  0.1059384 , -0.54841877,  0.18685764, -0.18323707,
         0.96891116, -1.8901319 ],
       [ 0.19160657,  0.18234367,  1.50083331,  0.69836101, -0.09119725,
        -0.01437648, -1.19306552],
       [ 2.20237169, -0.20527532, -0.44885624, -1.73121035,  0.91827558,
        -1.59569342,  0.94028598]])

In [145]:
data

array([[-0.85415932, -0.00908086,  0.19160657,  2.20237169],
       [ 0.77026201,  0.1059384 ,  0.18234367, -0.20527532],
       [ 0.75755567, -0.54841877,  1.50083331, -0.44885624],
       [-1.37573701,  0.18685764,  0.69836101, -1.73121035],
       [-1.34946915, -0.18323707, -0.09119725,  0.91827558],
       [ 0.67346525,  0.96891116, -0.01437648, -1.59569342],
       [-1.48070486, -1.8901319 , -1.19306552,  0.94028598]])

In [146]:
cond=names=='bob'

In [147]:
data[~cond]

array([[ 0.77026201,  0.1059384 ,  0.18234367, -0.20527532],
       [ 0.75755567, -0.54841877,  1.50083331, -0.44885624],
       [-1.34946915, -0.18323707, -0.09119725,  0.91827558],
       [ 0.67346525,  0.96891116, -0.01437648, -1.59569342],
       [-1.48070486, -1.8901319 , -1.19306552,  0.94028598]])

In [158]:
data[(names=='bob') | (names=='will')]

array([[-0.85415932, -0.00908086,  0.19160657,  2.20237169],
       [ 0.75755567, -0.54841877,  1.50083331, -0.44885624],
       [-1.37573701,  0.18685764,  0.69836101, -1.73121035],
       [-1.34946915, -0.18323707, -0.09119725,  0.91827558]])

In [159]:
mask=(names=='bob')|(names=='joe')
mask

array([ True,  True, False,  True, False,  True,  True])

In [161]:
data[~mask]

array([[ 0.75755567, -0.54841877,  1.50083331, -0.44885624],
       [-1.34946915, -0.18323707, -0.09119725,  0.91827558]])

In [163]:
arr=np.empty((8,4))

In [165]:
for i in range(8):
    arr[i]=i

In [166]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [167]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [168]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [169]:
arr[[1,5,7,2],[0,3,1,2]]

array([1., 5., 7., 2.])

In [171]:
arr.astype('int32')

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6],
       [7, 7, 7, 7]])

In [172]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [173]:
np.dot(arr.T,arr)

array([[140., 140., 140., 140.],
       [140., 140., 140., 140.],
       [140., 140., 140., 140.],
       [140., 140., 140., 140.]])